IF OBJECT_ID('STUDENT') IS NOT NULL
DROP TABLE STUDENT;
IF OBJECT_ID('STAFF') IS NOT NULL
DROP TABLE STAFF;
IF OBJECT_ID('SEMINAR') IS NOT NULL
DROP TABLE SEMINAR;
GO
CREATE TABLE STAFF_ALLOCATION(

, SemId NVARCHAR(50)
, StaffID NVARCHAR(1)
, FOREIGN KEY (SemId)
, FOREIGN KEY (StaffID)
);
CREATE TABLE ATTENDANCE(
Score INT
, SemId NVARCHAR(50)
, StudID NVARCHAR(1)
, PRIMARY KEY (S)
);