IF OBJECT_ID('STUDENT') IS NOT NULL
DROP TABLE STUDENT;
IF OBJECT_ID('STAFF') IS NOT NULL
DROP TABLE STAFF;
IF OBJECT_ID('SEMINAR') IS NOT NULL
DROP TABLE SEMINAR;
GO

CREATE TABLE STAFF_ALLOCATION( 
  SemId INT
, StaffID INT
, PRIMARY KEY (SemId, StaffID)
, FOREIGN KEY SemId REFERENCES SEMINAR
, FOREIGN KEY StaffID REFERENCES STAFF  
);
CREATE TABLE ATTENDANCE(
  Score NVARCHAR(50)
, SemId INT
, StuID INT
, PRIMARY KEY (StudID, SemId)
, FOREIGN KEY SemId REFERENCES SEMINAR
, FOREIGN KEY StuID REFERENCES STUDENT  
);
GOP